# Settings for all worlds
default:
  player:
    noDamage: false
    noHunger: false
    gameMode: '' # SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR, empty - don't change
  world:
    noBreak: false
    noPlace: false
    noInteract: false
    noFluidFlow: false
    noExplosions: false
    noWeather: false
    noFireSpread: false
    noLeafDecay: false
    noGrowth: false
    noMobGriefing: false
    noMobSpawn: false
    fixedTime:
      enabled: false
      time: 6000

# Overrides for specific worlds, only what differs from default
worlds: {}
# Example:
# worlds:
#   lobby:
#     player:
#       noDamage: true
#       gameMode: ADVENTURE
#     world:
#       noBreak: true
#       noPlace: true

configVersion: 1 # Format version of this file, do not change
